name: laughing_sharlene
services:
  archivist-es:
    cpu_shares: 90
    command: []
    container_name: archivist-es
    deploy:
      resources:
        limits:
          memory: 14930M
    environment:
      - ELASTIC_PASSWORD=verysecret
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - discovery.type=single-node
      - path.repo=/usr/share/elasticsearch/data/snapshot
      - xpack.security.enabled=true
    expose:
      - "9200"
    image: bbilly1/tubearchivist-es:latest
    labels:
      icon: https://icon.casaos.io/main/all/tubearchivist.png
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - type: bind
        source: /media/SSD-Storage/AppData/TubeArchivist/archivest-es
        target: /usr/share/elasticsearch/data
    ports: []
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
  archivist-redis:
    cpu_shares: 90
    command: []
    container_name: archivist-redis
    depends_on:
      archivist-es:
        condition: service_started
        required: true
    deploy:
      resources:
        limits:
          memory: 14930M
    expose:
      - "6379"
    image: redis:latest
    labels:
      icon: https://icon.casaos.io/main/all/tubearchivist.png
    restart: unless-stopped
    volumes:
      - type: bind
        source: /media/SSD-Storage/AppData/TubeArchivist/archivest-redis
        target: /data
    ports: []
    devices: []
    cap_add: []
    environment: []
    network_mode: bridge
    privileged: false
  tubearchivist:
    cpu_shares: 90
    command: []
    container_name: tubearchivist
    depends_on:
      archivist-es:
        condition: service_started
        required: true
      archivist-redis:
        condition: service_started
        required: true
    deploy:
      resources:
        limits:
          memory: 14930M
    environment:
      - ELASTIC_PASSWORD=verysecret
      - ES_URL=http://172.17.0.11:9200
      - HOST_GID=1000
      - HOST_UID=1000
      - REDIS_CON=redis://172.17.0.12:6379
      - TA_HOST=http://tubearchivist.local
      - TA_PASSWORD=verysecret
      - TA_USERNAME=tubearchivist
      - TZ=America/New_York
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8000/health
      timeout: 10s
      interval: 2m0s
      retries: 3
      start_period: 30s
    image: bbilly1/tubearchivist:latest
    labels:
      icon: https://icon.casaos.io/main/all/tubearchivist.png
    ports:
      - target: 8000
        published: "8000"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /media/SSD-Storage/Media/YouTube
        target: /youtube
      - type: bind
        source: /media/SSD-Storage/AppData/TubeArchivist/tubearchivest/cache
        target: /cache
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://icon.casaos.io/main/all/tubearchivist.png
  index: /
  is_uncontrolled: false
  port_map: "8000"
  scheme: http
  store_app_id: laughing_sharlene
  title:
    custom: ""
    en_us: tubearchivist
